"""Add contact_form_id to sites table

Revision ID: 11b0c2dda462
Revises: 
Create Date: 2026-02-01 16:01:10.520686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11b0c2dda462'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('email_threads', 'submission_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=False)
    # op.alter_column('email_threads', 'created_at',
    #            existing_type=mysql.DATETIME(),
    #            nullable=False)
    # op.create_index(op.f('ix_email_threads_submission_id'), 'email_threads', ['submission_id'], unique=False)
    # op.add_column('form_submissions', sa.Column('is_read', sa.Boolean(), nullable=True))
    # op.add_column('form_submissions', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # op.alter_column('form_submissions', 'site_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=False)
    # op.alter_column('form_submissions', 'is_active',
    #            existing_type=mysql.TINYINT(display_width=1),
    #            nullable=False)
    op.create_index(op.f('ix_form_submissions_site_id'), 'form_submissions', ['site_id'], unique=False)
    op.drop_index('unique_site_fluent_form', table_name='form_submissions')
    op.create_index('ix_site_form_entry', 'form_submissions', ['site_id', 'form_id', 'fluent_form_id'], unique=False)
    op.create_unique_constraint('unique_site_form_entry', 'form_submissions', ['site_id', 'form_id', 'fluent_form_id'])
    op.drop_column('form_submissions', 'read')
    op.add_column('site_assignments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('site_assignments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('site_assignments', 'site_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('site_assignments', 'role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('site_assignments', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.create_unique_constraint('uq_site_assignments_user_site', 'site_assignments', ['user_id', 'site_id'])
    op.add_column('sites', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('contact_form_id', sa.Integer(), nullable=True))
    op.add_column('sites', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sites', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('sites', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sites', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sites', 'api_key',
               existing_type=mysql.VARCHAR(length=255),
               type_=app.core.encryption.EncryptedString(length=1024),
               existing_nullable=True)
    op.alter_column('sites', 'api_secret',
               existing_type=mysql.VARCHAR(length=255),
               type_=app.core.encryption.EncryptedString(length=1024),
               existing_nullable=True)
    op.alter_column('sites', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.alter_column('sites', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('sites', 'api_secret',
               existing_type=app.core.encryption.EncryptedString(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('sites', 'api_key',
               existing_type=app.core.encryption.EncryptedString(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('sites', 'url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('sites', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('sites', 'updated_at')
    op.drop_column('sites', 'created_at')
    op.drop_column('sites', 'contact_form_id')
    op.drop_column('sites', 'last_synced_at')
    op.drop_constraint('uq_site_assignments_user_site', 'site_assignments', type_='unique')
    op.alter_column('site_assignments', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('site_assignments', 'role',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('site_assignments', 'site_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('site_assignments', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('site_assignments', 'created_at')
    op.add_column('form_submissions', sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint('unique_site_form_entry', 'form_submissions', type_='unique')
    op.drop_index('ix_site_form_entry', table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_site_id'), table_name='form_submissions')
    op.create_index('unique_site_fluent_form', 'form_submissions', ['site_id', 'fluent_form_id'], unique=True)
    op.alter_column('form_submissions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('form_submissions', 'site_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('form_submissions', 'updated_at')
    op.drop_column('form_submissions', 'is_read')
    op.drop_index(op.f('ix_email_threads_submission_id'), table_name='email_threads')
    op.alter_column('email_threads', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('email_threads', 'submission_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
