"""Add Gmail integration

Revision ID: b7565edcdb5c
Revises: 11b0c2dda462
Create Date: 2026-02-04 11:31:21.006650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7565edcdb5c'
down_revision: Union[str, None] = '11b0c2dda462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_threads', sa.Column('gmail_message_id', sa.String(length=255), nullable=True))
    op.add_column('email_threads', sa.Column('gmail_thread_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_email_threads_gmail_message_id'), 'email_threads', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_email_threads_gmail_thread_id'), 'email_threads', ['gmail_thread_id'], unique=False)
    op.add_column('form_submissions', sa.Column('gmail_thread_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_form_submissions_gmail_thread_id'), 'form_submissions', ['gmail_thread_id'], unique=False)

    op.create_table('gmail_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('client_secret', sa.String(length=1024), nullable=False),
    sa.Column('token_uri', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_credentials_id'), 'gmail_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_gmail_credentials_user_email'), 'gmail_credentials', ['user_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_credentials_user_email'), table_name='gmail_credentials')
    op.drop_index(op.f('ix_gmail_credentials_id'), table_name='gmail_credentials')
    op.drop_table('gmail_credentials')
    op.drop_index(op.f('ix_form_submissions_gmail_thread_id'), table_name='form_submissions')
    op.drop_column('form_submissions', 'gmail_thread_id')
    op.drop_index(op.f('ix_email_threads_gmail_thread_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_gmail_message_id'), table_name='email_threads')
    op.drop_column('email_threads', 'gmail_thread_id')
    op.drop_column('email_threads', 'gmail_message_id')
    # ### end Alembic commands ###
